### ISSUE TITLE
Consider supporting "tar.xz" format

### ISSUE THREAD

**Issue by dtolnay** [facebook/dotslash#10]
Official rustup components are available only in tar.gz and tar.xz. The tar.xz are significantly better compressed. `rustup` exclusively uses the tar.xz artifacts, and the plan is to stop providing tar.gz altogether (https://github.com/rust-lang/infra-team/issues/89).

https://static.rust-lang.org/dist/2023-12-28

They may or may not provide zstd in the future (https://github.com/rust-lang/infra-team/issues/97).

**Comment by bolinfest** [comment]
For sure, adding support is likely easy from a technical perspective, so it's more about what our tolerance is for increased binary size of DotSlash itself.

**Comment by bolinfest** [comment]
Interesting. My understanding is that `xz` priorities size compared to extraction time. For a build cluster talking to a CAS where presumably network is fast and disk is a bigger bottleneck, I feel like that would be a bad tradeoff. Though certainly if you on a personal machine and network isn't so great, then `xz` is probably what you want?
