### ISSUE TITLE
Latest release and docs should match

### ISSUE THREAD

**Issue by ethankhall** [facebook/dotslash#18]
👋 It looks like the docs match main, but not the latest version.

This means that the [docs](https://dotslash-cli.com/docs/dotslash-file/#artifact-format) show that `dotslash` supports `.tar.xz` however `0.2.0` does not. If I build against main, I'm able to use `tar.xz`.

Or could main be released so I can have people pull dotslash and use my `tar.xz` packages?

**Comment by bigfootjon** [comment]
@zertosh I think this would be fixed if we just release a new version right? Anything blocking that?

**Comment by zertosh** [comment]
We're good!

**Comment by bigfootjon** [comment]
I've released [`v0.3.0`](https://github.com/facebook/dotslash/releases/tag/v0.3.0) from HEAD so the docs are now up-to-date with the latest released version
