### ISSUE TITLE
Add guide for writing a `Provider`?

### ISSUE THREAD

**Issue by alilleybrinker** [facebook/dotslash#2]
It looks like new providers could be added in the following way:

1. Define a provider type which implements the `Provider` trait (see [`GitHubReleaseProvider`](https://github.com/facebook/dotslash/blob/main/src/github_release_provider.rs#L21-L56))
2. Wire it up in the [`get_provider` impl for `DefaultProviderFactory` in `main.rs`](https://github.com/facebook/dotslash/blob/main/src/main.rs#L47-L55).

It would be nice to have this reflected in the documentation!

__If y'all are open to contributions, I'd be happy to take a crack at it.__ Looks like the docs themselves are built with Docusaurus, which shouldn't be difficult to work with.

My only question to validate at the moment is the proper handling of the provider config. It looks like the intent is that the provider config is given as a valid "loosely parsed" JSON value, which the provider itself is then able to deserialize into any specific structure it likes. Do I have that right?

**Comment by alilleybrinker** [comment]
(Disclosure: my interest here is that it would be nice to add a GitLab provider which works similarly to the GitHub provider, downloading released artifacts built by CI from a GitLab instance)

**Comment by bolinfest** [comment]
From the [current docs](https://dotslash-cli.com/docs/dotslash-file/#providers):

> (At the time of this writing, there is no way to add custom providers without forking DotSlash.)

Relatedly, I don't think that we are ready to commit to the contract of `Provider` just yet. To be clear, I am open to considering https://github.com/facebook/dotslash/pull/3, but it would have to be a built-in provider for now. That way, any changes to the `Provider` trait could be made atomically with their implementations.

> My only question to validate at the moment is the proper handling of the provider config. It looks like the intent is that the provider config is given as a valid "loosely parsed" JSON value, which the provider itself is then able to deserialize into any specific structure it likes. Do I have that right?

Yes, that is correct.

**Comment by alilleybrinker** [comment]
Totally makes sense regarding not wanting to commit to the `Provider` design at the moment. Perhaps then it doesn't make sense to document how to implement a `Provider` (the design today is also simple enough that a reasonably capable Rust programmer _should_ in theory be able to figure out what's needed with relative ease). So long as the process of adding one stays the same, you could also always point people to this issue and to the draft PR for a GitLab Releases provider to show what's necessary.

There's also the fact that so far the docs for Dotslash appear to be focused on _users_ of it, not _contributors_ to it, so docs on how to write a `Provider` would be a little out of place there.

Thanks! Happy to consider this issue resolved for now then.
