### ISSUE TITLE
Release status?

### ISSUE THREAD

**Issue by bolinfest** [facebook/dotslash#21]
It looks like there is a v0.3.0 release on GitHub:

https://github.com/facebook/dotslash/releases/tag/v0.3.0

Though crates.io is still v0.2.0:

https://crates.io/crates/dotslash

The additional support for `.xz` in v0.3.0 seems like a win, though I expect `.zip` support is more impactful for users, so it would be helpful to drive the associated PR to some sort of resolution:

https://github.com/facebook/dotslash/pull/13

**Comment by bigfootjon** [comment]
Oops my bad, I didn't realize we needed to push the crate separately. I've done so now: https://crates.io/crates/dotslash/versions

> though I expect .zip support is more impactful for users, so it would be helpful to drive the associated PR to some sort of resolution:

That's in-progress, no harm in more releases though :)

**Comment by bolinfest** [comment]
FYI, before leaving Meta, I wrote up a doc (I think it's an internal-only Markdown file rather than a wiki page) listing the steps required to do a release. I believe it also mentions Homebrew and had some notes about Linux distros.

@bigfootjon Can you please verify that you can find the doc and did everything on the list? Ideally the doc would be turned into a script to make it turnkey, but that might be challenging...

**Comment by bolinfest** [comment]
It appears Homebrew was updated here, fwiw: https://github.com/Homebrew/homebrew-core/commit/19703136e7dc3da1563da81054a07244e858509d

**Comment by bolinfest** [comment]
Actually, I'm not sure that was done correctly...

https://github.com/facebook/dotslash/issues/23
