### ISSUE TITLE
Fix CI: macos-13 build appears to be failing

### ISSUE THREAD

**Issue by bolinfest** [facebook/dotslash#25]
CI appears to be failing since this commit titled "Rust 1.77 clippy fixes:"

https://github.com/facebook/dotslash/commit/018ee4cc189a6e7b05b9e53273f5be3cc7a81fd6

**Comment by bolinfest** [comment]
This should probably block the v0.4.0 release? /cc @bigfootjon

**Comment by zertosh** [comment]
Looking
