### ISSUE TITLE
Please don't retag releases

### ISSUE THREAD

**Issue by alerque** [facebook/dotslash#26]
Downstream packager here. Every time an upstream project retags something that already went out we have to do a lot of extra work to verify what changed and why and that it isn't malicious. Versioned tags are meant to be immutable. Please just bump the patch version and try again if/when something goes wrong with the release process or a bug is found early on.

**Comment by zertosh** [comment]
cc: @bigfootjon

**Comment by zertosh** [comment]
Thank you! Sorry about the troubles. Will do!
