### ISSUE TITLE
Suggestion: allow leading `#` comments in dotslash files

### ISSUE THREAD

**Issue by bradzacher** [facebook/dotslash#31]
Sometimes you need to hand-craft a dotslash config file and sometimes it's nice to add some commentary about said file.

For example I was authoring a config for `gofmt` and wanted to document how I got all the values to make it easy for the next person to update it in future.

Currently when I added a `#` line immediately after the hashbang, dotslash emitted the following:
```
dotslash error: problem with `/path/to/gofmt`
caused by: failed to parse DotSlash file
caused by: expected value at line 1 column 1
```

**Comment by dtolnay** [comment]
The comment syntax is `//` and `/*`…`*/`. See https://dotslash-cli.com/docs/dotslash-file.

**Comment by bradzacher** [comment]
Ahh I completely missed the tip block in the docs

```
TIP
The JSON payload in a DotSlash file is parsed with a lenient JSON parser that allows for trailing commas as well as // and /*-style comments.
```

I'd just assumed that the instances of `//` and `/**/` were for docs purposed, not that they were valid syntax.
