### ISSUE TITLE
Support zip in Artifact Format

### ISSUE THREAD

**Issue by hn8** [facebook/dotslash#8]
Will you be open to PR for supporting zip format? For example https://github.com/dprint/dprint/releases. Thanks!

**Comment by bolinfest** [comment]
I feel like we tried supporting zip internally at Meta and ran into some issues. Something like the zip Rust crate didn't support all zip files we tested it with?

Hopefully @zertosh remembers...

**Comment by zertosh** [comment]
We tried [zip-rs](https://github.com/zip-rs/zip) when they were at v0.5.0 (mid-2019). At the time it had terrible perf and it didn't handle symlinks. I don't know if the issues have been resolved. It's worth revisiting though.

**Comment by abhinav** [comment]
Took an initial stab at this using zip-rs. https://github.com/facebook/dotslash/pull/13
It worked fine with the dprint archive; I didn't test it with anything else.

**Comment by abhinav** [comment]
@hn8 Please re-open the issue. The change hasn't been merged into the official repository yet.
